#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# zmodload zsh/zprof && zprof

if [ -f /etc/profile.d/vte.sh ]; then
  . /etc/profile.d/vte.sh
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$HOME/bin:$PATH
export EDITOR=vi

bindkey -v
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^F' forward-word
bindkey '^B' backward-word

dir=$(dirname "$(readlink -f $0)")
source "${dir}/alias.sh"
source "${dir}/peco.sh"
source "${dir}/lang.sh"
source "${dir}/tool.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/tech/.gcloud/path.zsh.inc' ]; then . '/home/tech/.gcloud/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/tech/.gcloud/completion.zsh.inc' ]; then . '/home/tech/.gcloud/completion.zsh.inc'; fi

